# Generated by Django 4.2.10 on 2025-09-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cuisine',
            options={'ordering': ['name']},
        ),
    ]
