# Generated by Django 4.2.10 on 2025-09-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
